tst:
	stack build :test;node .stack-work/install/x86_64-osx/lts-7.19/ghcjs-0.2.1.9007019_ghc-8.0.1/bin/test.jsexe/all.js

dev:
	stack build :test --fast --file-watch --exec 'node .stack-work/install/x86_64-osx/lts-7.19/ghcjs-0.2.1.9007019_ghc-8.0.1/bin/test.jsexe/all.js'
